### ISSUE TITLE
Compatible with IBM Blockchain Platform 2.0

### ISSUE THREAD

**Issue by sandra-calvo** [IBM/car-auction-network-fabric-node-sdk#5]
Hi, 

can you make this compatible with the new IBP? 
Thanks!

**Comment by horeaporutiu** [comment]
@sandra-calvo 

Not sure if this will be upgraded or not, since the chaincode is almost identical to this sample https://github.com/IBM/fabcar-blockchain-sample

It doesn't really make sense to update this to IBP 2.0 given that the chaincode is so similar and the steps for connecting to IBP 2.0 would be the same as well.

Please follow the fabcar repo for connecting to IBM Blockchain 2.0.

**Comment by ljbennett62** [comment]
@sandra-calvo @horeaporutiu - so this was updated for Think to IBP2.0: https://developer.ibm.com/patterns/write-a-smart-contract-for-the-fabcarcommercial-paper-or-iks-cluster-with-saas-v2-beta-network-think/.  I believe they are one in the same
